name: Build Examples
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-examples:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # Newest supported configuration
          - go-version: '~1.21.0'
            tinygo-version: '0.30.0'
          # Oldest supported configuration
          - go-version: '~1.19.0'
            tinygo-version: '0.28.1'

    steps:
      - name: Checkout fastly/compute-sdk-go
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install TinyGo
        uses: ./.github/actions/install-tinygo
        with:
          tinygo-version: ${{ matrix.tinygo-version }}

      - name: Build examples Go
        env:
          GOARCH: wasm
          GOOS: wasip1
        run: |
          for i in _examples/*/; do
            echo ${GITHUB_WORKSPACE}/$i
            cd ${GITHUB_WORKSPACE}/$i && go build -tags fastlyinternaldebug
          done

      - name: Build examples TinyGo
        run: |
          for i in _examples/*/; do
            echo ${GITHUB_WORKSPACE}/$i
            cd ${GITHUB_WORKSPACE}/$i && tinygo build -target=wasi -tags fastlyinternaldebug
          done
