name: Build Examples
on: [push]
jobs:
  build-examples-tinygo:
    strategy:
      matrix:
        include:
          # Newest supported configuration
          - go-version: '~1.21.0'
            tinygo-version: '0.30.0'
          # Oldest supported configuration
          - go-version: '~1.19.0'
            tinygo-version: '0.28.1'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fastly/compute-sdk-go
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
         go-version: ${{ matrix.go-version }}
      - name: Install TinyGo
        uses: ./.github/actions/install-tinygo
        with:
          tinygo-version: ${{ matrix.tinygo-version }}
      - name: Build examples
        run: |
          for i in _examples/*/; do
            echo ${GITHUB_WORKSPACE}/$i
            cd ${GITHUB_WORKSPACE}/$i && tinygo build -target=wasi -tags fastlyinternaldebug
          done
  build-examples-go:
    strategy:
      matrix:
        go-version: ['~1.21.0']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fastly/compute-sdk-go
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
         go-version: ${{ matrix.go-version }}
      - name: Build examples
        run: |
          for i in _examples/*/; do
            echo ${GITHUB_WORKSPACE}/$i
            cd ${GITHUB_WORKSPACE}/$i && env GOARCH=wasm GOOS=wasip1 go build -tags fastlyinternaldebug
          done
