name: Integration Tests
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  integration-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # Newest supported configuration
          - go-version: 'stable'
            tinygo-version: '0.31.0'
          # Oldest supported configuration
          - go-version: 'oldstable'
            tinygo-version: '0.28.1'

    steps:
      - name: Checkout fastly/compute-sdk-go
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install TinyGo
        uses: ./.github/actions/install-tinygo
        with:
          tinygo-version: ${{ matrix.tinygo-version }}

      - name: Setup Fastly CLI
        uses: fastly/compute-actions/setup@v7

      - name: Install Viceroy ${{ env.VICEROY_VERSION }}
        shell: 'bash'
        env:
          VICEROY_VERSION: 0.9.7
        run: |
          echo "Install Viceroy ${{ env.VICEROY_VERSION }}..."
          wget https://github.com/fastly/Viceroy/releases/download/v${{ env.VICEROY_VERSION }}/viceroy_v${{ env.VICEROY_VERSION }}_linux-amd64.tar.gz
          mkdir -p $HOME/bin
          tar -xzf viceroy_v${{ env.VICEROY_VERSION }}_linux-amd64.tar.gz --directory $HOME/bin
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Check our dependencies
        run: |
          go version
          tinygo version
          fastly version
          viceroy --version

      - name: Run Integration Tests Go
        env:
          RUST_LOG: viceroy=info,viceroy-lib=info
          GOARCH: wasm
          GOOS: wasip1
        run: |
          for i in integration_tests/*/; do
            echo ${GITHUB_WORKSPACE}/$i
            cd ${GITHUB_WORKSPACE}/$i && go test -v -tags fastlyinternaldebug -exec "viceroy run -C fastly.toml" ./...
          done

      - name: Run Integration Tests TinyGo
        env:
          RUST_LOG: viceroy=info,viceroy-lib=info
        run: tinygo test -v -tags fastlyinternaldebug -target=fastly-compute.json ./integration_tests/...
