name: Validate
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: go vet
        run: go vet ./...

      - name: staticcheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          staticcheck ./...

      - name: nilness
        run: |
          go install golang.org/x/tools/go/analysis/passes/nilness/cmd/nilness@master
          nilness ./...

      - name: ineffassign
        run: |
          go install github.com/gordonklaus/ineffassign@latest
          ineffassign ./...

  test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - uses: ./.github/actions/install-tinygo
        with:
          tinygo-version: '0.31.2'

      - name: Set up Wasmtime
        uses: bytecodealliance/actions/wasmtime/setup@v1

      - name: Check our dependencies
        run: |
          go version
          tinygo version
          wasmtime --version

      - name: Tests - Go
        run: go test -v -race -tags="fastlyinternaldebug nofastlyhostcalls" ./...

      - name: Tests - TinyGo
        env:
          GOARCH: wasm
          GOOS: wasip1
        run: tinygo test -v -tags="fastlyinternaldebug nofastlyhostcalls" ./...
